version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "3000:3000"
    restart: always
    depends_on:
      - redis-server
    environment:
      - REDIS_HOST=redis-server:6379

  redis-server:
    image: "redis:alpine"
    ports:
      - "6379:6379"