version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "3000:3000"
    restart: always
    depends_on:
      - redis-server
    environment:
      - REDIS_HOST=redis-server:6377

  redis-server:
    image: "redis:alpine"
    command: --port 6377
    ports:
      - "6377:6377"
    expose:
      - "6377"