// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: proto/otp.proto

package grpc_from0

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadGenerateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
}

func (x *PayloadGenerateRequest) Reset() {
	*x = PayloadGenerateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_otp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadGenerateRequest) ProtoMessage() {}

func (x *PayloadGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadGenerateRequest.ProtoReflect.Descriptor instead.
func (*PayloadGenerateRequest) Descriptor() ([]byte, []int) {
	return file_proto_otp_proto_rawDescGZIP(), []int{0}
}

func (x *PayloadGenerateRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type PayloadGenerateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *PayloadGenerateResponse) Reset() {
	*x = PayloadGenerateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_otp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadGenerateResponse) ProtoMessage() {}

func (x *PayloadGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadGenerateResponse.ProtoReflect.Descriptor instead.
func (*PayloadGenerateResponse) Descriptor() ([]byte, []int) {
	return file_proto_otp_proto_rawDescGZIP(), []int{1}
}

func (x *PayloadGenerateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type PayloadVerificateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Otp   string `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
}

func (x *PayloadVerificateRequest) Reset() {
	*x = PayloadVerificateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_otp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadVerificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadVerificateRequest) ProtoMessage() {}

func (x *PayloadVerificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadVerificateRequest.ProtoReflect.Descriptor instead.
func (*PayloadVerificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_otp_proto_rawDescGZIP(), []int{2}
}

func (x *PayloadVerificateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PayloadVerificateRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type PayloadVerificateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PayloadVerificateResponse) Reset() {
	*x = PayloadVerificateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_otp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayloadVerificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadVerificateResponse) ProtoMessage() {}

func (x *PayloadVerificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayloadVerificateResponse.ProtoReflect.Descriptor instead.
func (*PayloadVerificateResponse) Descriptor() ([]byte, []int) {
	return file_proto_otp_proto_rawDescGZIP(), []int{3}
}

func (x *PayloadVerificateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PayloadVerificateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_otp_proto protoreflect.FileDescriptor

var file_proto_otp_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3b, 0x0a, 0x16, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2f, 0x0a, 0x17, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x42, 0x0a, 0x18, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6f, 0x74, 0x70, 0x22, 0x4f, 0x0a, 0x19, 0x50, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0xa9, 0x01, 0x0a, 0x07,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x4b, 0x0a, 0x08, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x51, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f, 0x6e, 0x6b, 0x72, 0x75, 0x73, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x66, 0x72, 0x6f, 0x6d, 0x30, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x72,
	0x6f, 0x6d, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_otp_proto_rawDescOnce sync.Once
	file_proto_otp_proto_rawDescData = file_proto_otp_proto_rawDesc
)

func file_proto_otp_proto_rawDescGZIP() []byte {
	file_proto_otp_proto_rawDescOnce.Do(func() {
		file_proto_otp_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_otp_proto_rawDescData)
	})
	return file_proto_otp_proto_rawDescData
}

var file_proto_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_otp_proto_goTypes = []interface{}{
	(*PayloadGenerateRequest)(nil),    // 0: proto.PayloadGenerateRequest
	(*PayloadGenerateResponse)(nil),   // 1: proto.PayloadGenerateResponse
	(*PayloadVerificateRequest)(nil),  // 2: proto.PayloadVerificateRequest
	(*PayloadVerificateResponse)(nil), // 3: proto.PayloadVerificateResponse
}
var file_proto_otp_proto_depIdxs = []int32{
	0, // 0: proto.Payload.Generate:input_type -> proto.PayloadGenerateRequest
	2, // 1: proto.Payload.Verificate:input_type -> proto.PayloadVerificateRequest
	1, // 2: proto.Payload.Generate:output_type -> proto.PayloadGenerateResponse
	3, // 3: proto.Payload.Verificate:output_type -> proto.PayloadVerificateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_otp_proto_init() }
func file_proto_otp_proto_init() {
	if File_proto_otp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_otp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadGenerateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_otp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadGenerateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_otp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadVerificateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_otp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayloadVerificateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_otp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_otp_proto_goTypes,
		DependencyIndexes: file_proto_otp_proto_depIdxs,
		MessageInfos:      file_proto_otp_proto_msgTypes,
	}.Build()
	File_proto_otp_proto = out.File
	file_proto_otp_proto_rawDesc = nil
	file_proto_otp_proto_goTypes = nil
	file_proto_otp_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PayloadClient is the client API for Payload service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PayloadClient interface {
	Generate(ctx context.Context, in *PayloadGenerateRequest, opts ...grpc.CallOption) (*PayloadGenerateResponse, error)
	Verificate(ctx context.Context, in *PayloadVerificateRequest, opts ...grpc.CallOption) (*PayloadVerificateResponse, error)
}

type payloadClient struct {
	cc grpc.ClientConnInterface
}

func NewPayloadClient(cc grpc.ClientConnInterface) PayloadClient {
	return &payloadClient{cc}
}

func (c *payloadClient) Generate(ctx context.Context, in *PayloadGenerateRequest, opts ...grpc.CallOption) (*PayloadGenerateResponse, error) {
	out := new(PayloadGenerateResponse)
	err := c.cc.Invoke(ctx, "/proto.Payload/Generate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payloadClient) Verificate(ctx context.Context, in *PayloadVerificateRequest, opts ...grpc.CallOption) (*PayloadVerificateResponse, error) {
	out := new(PayloadVerificateResponse)
	err := c.cc.Invoke(ctx, "/proto.Payload/Verificate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayloadServer is the server API for Payload service.
type PayloadServer interface {
	Generate(context.Context, *PayloadGenerateRequest) (*PayloadGenerateResponse, error)
	Verificate(context.Context, *PayloadVerificateRequest) (*PayloadVerificateResponse, error)
}

// UnimplementedPayloadServer can be embedded to have forward compatible implementations.
type UnimplementedPayloadServer struct {
}

func (*UnimplementedPayloadServer) Generate(context.Context, *PayloadGenerateRequest) (*PayloadGenerateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Generate not implemented")
}
func (*UnimplementedPayloadServer) Verificate(context.Context, *PayloadVerificateRequest) (*PayloadVerificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verificate not implemented")
}

func RegisterPayloadServer(s *grpc.Server, srv PayloadServer) {
	s.RegisterService(&_Payload_serviceDesc, srv)
}

func _Payload_Generate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayloadGenerateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadServer).Generate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Payload/Generate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadServer).Generate(ctx, req.(*PayloadGenerateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Payload_Verificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayloadVerificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadServer).Verificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Payload/Verificate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadServer).Verificate(ctx, req.(*PayloadVerificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Payload_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Payload",
	HandlerType: (*PayloadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Generate",
			Handler:    _Payload_Generate_Handler,
		},
		{
			MethodName: "Verificate",
			Handler:    _Payload_Verificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/otp.proto",
}
